### ISSUE TITLE
Issues with E-paper readers

### ISSUE THREAD

**Issue by shafr** [BlueHatbRit/mdpdf#107]
Hello, I'm using mdpdf [to generate pdf's](https://github.com/shafr/CEH-in-bullet-points/actions).
Reading on PC/mobile phone is ok, but when I upload books to e-ink readers, i'm getting starange behaviour that black is not black but gray, so it's very hard to read from the book.
![IMG_20210916_115319](https://user-images.githubusercontent.com/26896695/133591661-ceeca79c-905c-441c-a640-f23730e96e1a.jpg)
 
vs 

![image](https://user-images.githubusercontent.com/26896695/133591840-55f19e8c-7a44-4fda-84cc-daf8fb241e56.png)

What is the correct way to change font type / font color / font size ? Are there any examples of that ? (Is that the css section?)

**Comment by BlueHatbRit** [comment]
The default styles applied are pulled from GitHub's markdown styling so the text isn't hard black but actually a dark grey which is probably causing the problem here. You can use the `--style`  flag to provide your own CSS sheet as shown in one of the examples https://github.com/BlueHatbRit/mdpdf#example-usage.

When using the CLI, passing in your own CSS will disable the default github style rather than stacking on-top of it. If you like the style but just want to change the font colour I'd suggest taking a copy of our default style sheet, amending it to fit your needs, and passing that in with the `--style` flag.

That stylesheet can be found here https://github.com/BlueHatbRit/mdpdf/blob/master/src/assets/github-markdown-css.css

**Comment by shafr** [comment]
Thank you, that was very useful!

**Comment by BlueHatbRit** [comment]
No problem, thanks for closing the issue :)
