### ISSUE TITLE
Syntax highlighting on windows

### ISSUE THREAD

**Issue by BlueHatbRit** [BlueHatbRit/mdpdf#11]
Referring back to #7, we ended up disabling syntax highlighting on Windows. This was a bi-product of correcting some exceptions.

It's still not clear why syntax highlighting is no longer working on Windows. If someone could track it down, it would be great!

## How syntax highlighting works

We use [hljs (highlight.js)](https://highlightjs.org/) which we include in all the code which is pushed into PhantomJS (headless browser). This should action syntax highlighting and it does in the debug HTML output, however for some reason under PhantomJS it's not rendering out the highlights in the final PDF save.

PhantomJS is a headless browser wrapped into a node module, it's used within the `html-pdf` package we use. It enables us to kick up a browser, push in the html, and get a PDF out afterwards as well as having some header and footer support we make use of.

**Comment by IonicaBizau** [comment]
@BlueHatbRit Hey! I'm really happy to see you're using [`showdown-emoji`](https://github.com/Bloggify/showdown-emoji) which I have just open-sourced and published it (it was on `npm` for a while but it wasn't on GitHub).

Also, I open-sourced [`showdown-highlight`](https://github.com/Bloggify/showdown-highlight) which uses `highlight.js`.

I think that will help since it will generate the highlighting *on the server*, not on the client. Once added, `showdown-highlight` will convert the code blocks (`pre`) into highlighted code blocks.
That means we still need the highlight.js CSS, but not the JavaScript on the client.

I don't have a Windows machine around...

Keep up the good work! 👍

**Comment by BlueHatbRit** [comment]
@IonicaBizau thanks so much for open sourcing both of those modules. When I get a chance I'll see about bringing in `showdown-highlight`. That may well fix the issues we're having.

The emoji module is great as well, thanks for opening it up. I might look at contributing some shorthand emoji's when I get a chance.

Thanks bringing all of this to my attention, keep up the good work yourself!

**Comment by IonicaBizau** [comment]
Great! 😁 Thanks for the kind words! ✨

**Comment by BlueHatbRit** [comment]
Note to self: When i get time to look at it, it might also be worth me checking out http://prismjs.com/download.html to see if that works as well. Right now I'm leaning towards showdown-highlight if it works well and provides good language coverage.

**Comment by BlueHatbRit** [comment]
This should be resolved with the 2.0.0 Puppeteer based release but please check the release notes before upgrading!
