### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by adriaanvanrossum** [BlueHatbRit/mdpdf#112]
Hey @BlueHatbRit,

Would you be open to upgrading the dependencies to the latest versions? For example, it is still using puppeteer 2, which is probably a lot less secure than the latest version.

I see a few open PRs, so before I do any work, I would love to check in with you.

Regards,

**Comment by BlueHatbRit** [comment]
Hi @adriaanvanrossum, I'd be open to reviewing and merging some PRs but to be honest I don't have time to do them myself right now, especially if they deal with larger breaking changes to various apis.

If you've got time and would like to submit some fixes you're very welcome to and I'll review them as soon as I can. Just as a disclaimer though, I am about to move house so there may be a few days / weeks where I don't have much in the way of a stable internet connection. None the less, I'll do my best with any PR's that do get raised.

In terms of existing PR's, I believe the reason I didn't merge https://github.com/BlueHatbRit/mdpdf/pull/105 is because it was just the package upgrade and didn't address any of the changes required although it's been a while so I'll try and take a look at it again when I get a moment.

**Comment by krzysztof-o** [comment]
Upgrading meow in #105 would fix one of the audit errors returned by `npm audit`. Would be great if you could merge that one plus `cheerio` dependency is also marked as High issue.

```
# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install mdpdf@1.1.1, which is a breaking change
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    cheerio  0.19.0 - 1.0.0-rc.3
    Depends on vulnerable versions of css-select
    node_modules/cheerio
      mdpdf  >=0.1.6
      Depends on vulnerable versions of cheerio
      Depends on vulnerable versions of meow
      node_modules/mdpdf

trim-newlines  <3.0.1
Severity: high
Uncontrolled Resource Consumption in trim-newlines - https://github.com/advisories/GHSA-7p7h-4mm5-852v
fix available via `npm audit fix --force`
Will install mdpdf@1.1.1, which is a breaking change
node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  Depends on vulnerable versions of yargs-parser
  node_modules/meow
    mdpdf  >=0.1.6
    Depends on vulnerable versions of cheerio
    Depends on vulnerable versions of meow
    node_modules/mdpdf

yargs-parser  6.0.0 - 13.1.1
Severity: moderate
Prototype Pollution in yargs-parser - https://github.com/advisories/GHSA-p9pc-299p-vxgp
fix available via `npm audit fix --force`
Will install mdpdf@1.1.1, which is a breaking change
node_modules/meow/node_modules/yargs-parser
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  Depends on vulnerable versions of yargs-parser
  node_modules/meow
    mdpdf  >=0.1.6
    Depends on vulnerable versions of cheerio
    Depends on vulnerable versions of meow
    node_modules/mdpdf

7 vulnerabilities (1 moderate, 6 high)
```

**Comment by BlueHatbRit** [comment]
I've upgraded a bunch of the deps today, the outstanding one is `meow` which now requires using esmodules which would need us to convert the project over to that. I started a branch but it's going to take a while to debug and get right so it may not happen quickly unless someone else wants to take that on.

**Comment by BlueHatbRit** [comment]
I've done an upgrade of all dependencies on master now. We should be on the latest for everything now. Those upgrades will be bundled with the next release (3.0.2).
