### ISSUE TITLE
Make first argument source by default

### ISSUE THREAD

**Issue by abejfehr** [BlueHatbRit/mdpdf#2]
I don't know how easy this is (I guess it depends on how the arguments are parsed) but I think it would be convenient to have the first argument always be the .md file to be converted.

So something like:

    mdpdf --source thing.md <other options>

Would become:

    mdpdf thing.md <other options>

I'd be happy to investigate, develop it and make a pull request if this idea were welcomed.

**Comment by BlueHatbRit** [comment]
I was thinking the exact same but I haven't had time to get around to it yet. I did it this way because it was quick using the first args package I came across (npmjs.com/package/yargs) but this is not the best option.

I spent a bit of time looking at a module which I use a lot (https://github.com/TryGhost/knex-migrator) and how they do arguments using npmjs.com/package/commander but I'm not sure if this is the best approach.

What were you thinking @abejfehr? A pull request would be very welcome!

**Comment by BlueHatbRit** [comment]
I've switched the argument parsing module out from yargs to meow, this has allowed for a much nicer syntax of something like `$ mdpdf README.md --style md-styles.css --debug` or `$ mdpdf README.md output.pdf`

Hopefully this resolves the issue, it should be in release 1.2.1 which is now on NPM.
