### ISSUE TITLE
:word: converts to blank image if not actual emoji tag

### ISSUE THREAD

**Issue by travs** [BlueHatbRit/mdpdf#30]
Moved here at your request; good luck with the move! 😄 
cc: https://github.com/travs/markdown-pdf/issues/166

**Comment by BlueHatbRit** [comment]
It seems showdown-emoji is attempting to replace any word wrapped in colons (with no spaces) with an emoji image, even if the emoji doesn't exist.

We probably want to create a patch for that repo which fixes this and stops the replacement of text when an image isn't found.

**Comment by flakrat** [comment]
I encountered this while using markdown-pdf plugin in Atom.io editor.

In my case the issue was happening from within a code block (note the trailing hash tag was added to allow the back ticks to print in the ticket, not part of original code)

```
```shell
FQDN=`hostname -f  | tr '[:upper:]' '[:lower:]'`
```#
```
This is how it renders (as described in the original issue text:
![image](https://user-images.githubusercontent.com/1587409/32304900-b3f62a80-bf48-11e7-81b0-8b69ea9bea47.png)

My expectation was that emoji conversion would be ignored when inside of a code block. Does that make sense or am I myopic in my view :-)

**Comment by BlueHatbRit** [comment]
Hi there @flakrat, I think you're totally right that it should be ignored in code blocks. However I think it's a slightly bigger issue in that it should probably render words for any un-recognised emoji.

As this is a problem with showdown-emoji I need to find some time to pick up that project, figure it out how it's working and try and get a fix submitted which we can pull into this (or fork it). Sadly I don't have a huge amount of time at the moment, but I should be able to take quick look this evening to see if there's a fix that can be rolled.

**Comment by BlueHatbRit** [comment]
Had another instance of this, I'm going to release a new version of mdpdf in the next few days which turns off emoji support by default. The flag will now be to enable emoji conversion with a link to this issue until we can solve it in showdown-emoji.

I've opened an issue over on showdown-emoji to start working on this, but I'm still waiting for a reply on my proposed method of solving this.

**Comment by BlueHatbRit** [comment]
Thanks to IonicaBizau on showdown-emoji, this has now been resolved. The version has been bumped from their end as a patch so any npm install commands will grab the new one without me doing a release.

I'll leave the flags as they are for now and I'll close this one off. Thanks for all the reports.

**Comment by istvanszoboszlai** [comment]
I have tested it, and I can confirm that it is fixed. Thanks!

**Comment by BlueHatbRit** [comment]
Brilliant, cheers @istvanszoboszlai!
