### ISSUE TITLE
Successive bold text sections cause underscores to be rendered strangely

### ISSUE THREAD

**Issue by travs** [BlueHatbRit/mdpdf#41]
[Someone](https://github.com/travs/markdown-pdf/issues/182) in `markdown-preview` found a strange edge-case or something.

```
# markdown
__this is bold__ __this is also bold__

# renders as (in bold)
this is bold__ __this is also bold
```

Unsure if this is expected behaviour, but seems like it is not.

**Comment by BlueHatbRit** [comment]
Hm, underscores really denote italics so the fact it's going bold is interesting. As discussed in the past, mdpdf uses Showdown to convert markdown to html, so this would most likely be upstream. Though the plan in the not too distant future is to pull this into mdpdf rather than using showdown so we have greater control.

I'll have a test with showdown and see what it spits out without mdpdf to make sure it's not my screw up with any styles or anything, then I'll look at pushing this upstream to ask for comment.

**Comment by BlueHatbRit** [comment]
Late to the ball game with this one but I'm spring cleaning. It seems Showdown gives us this:

<img width="695" alt="screenshot 2019-01-19 at 21 30 36" src="https://user-images.githubusercontent.com/1068477/51432557-801efb00-1c31-11e9-82ea-4d8673e63c43.png">

The PDF's render in a similar fashion but not identically. I'm going to go and update Showdown and see if that fixes the issue.

**Comment by BlueHatbRit** [comment]
MDPDF 2.0.1 now matches the latest Showdown output shown in the above comment, this was done by updating to the latest version of Showdown. If this isn't the expected behaviour then we should look at reporting it to that project and see if they think this is how the md spec should be interpreted.
