### ISSUE TITLE
[Suggestion] Add a Dockerfile to the project

### ISSUE THREAD

**Issue by enric1994** [BlueHatbRit/mdpdf#50]
I  have created a Docker image to avoid installing node and the dependencies:
```
FROM node:8.11.1
RUN npm i -g phantomjs-prebuilt --unsafe-perm --silent
RUN npm install mdpdf -g
```
To use it, I setup an alias like this one:
`alias mdpdf="docker run --rm -it -w /data -v $(pwd):/data enric1994/mdpdf mdpdf"`

Then, I run: `mdpdf README.md`

Hope it help,

Enric

**Comment by BlueHatbRit** [comment]
Thanks @enric1994, this seems like an interesting way of using mdpdf, thanks for sharing it! Since this is primarily a CLI tool and node library I don't plan on bundling this into a docker container at the moment, it feels quite overkill for processing a markdown file.

It's a nice way to use it if you don't want to install the dependencies which I appreciate, but I don't think maintaining a docker image is something I want to take on with mdpdf at the moment. Feel free to continue to use it that way if you like, I see no reason it won't continue to work with later versions, but I can't promise that later versions of mdpdf won't break it somehow. As a result you might want to lock down the mdpdf version in your dockerfile.

If enough people came forward wanting to use it this way then I'd definitely consider making an officially supported container, but that doesn't seem to be the case at the moment.

Thanks for sharing!

**Comment by PeterDaveHello** [comment]
I'd like to see if this tool can be easily used via Docker, would you like to accept a pull request for it @BlueHatbRit?

**Comment by BlueHatbRit** [comment]
@PeterDaveHello yeah go for it, happy to accept a PR for this!

**Comment by PeterDaveHello** [comment]
Thanks! PR #179 sent!
