### ISSUE TITLE
command line script closes the batch script

### ISSUE THREAD

**Issue by GiggioG** [BlueHatbRit/mdpdf#92]
I have a back script, that uses `mdpdf file.md export\pfile.pdf` and the some other batch code,  but the other batch code doesn't get executed. I looked at the mdpdf.cmd file in `C:\Users\USERNAMEHERE\AppData\Roaming\npm`, but it uses `EXIT /B`, but I thought that was supposed to quit only the current batch script `(mdpdf.cmd)`, and not the big one.

**Comment by BlueHatbRit** [comment]
Hey I'm really sorry but I don't know much about windows batch files, it's been years since I've done any dev work on a windows machine. I've not had any issues the few times I've used mdpdf on windows though, could you provide a full script that reproduces the problem and I'll try and take a look on a family members computer?

**Comment by GiggioG** [comment]
Sorry that I didn't close it sooner. I now know what I did wrong. For everyone, link to stackoverflow [here](https://giggiog.github.io/rikrold.html?https://stackoverflow.com/questions/61954337/mdpdf-closes-batch-script). I will now be closing this issue. Bye.
